### ISSUE TITLE
ShouldBeBanned

### ISSUE THREAD

**Issue by dorleitman** [sagioto/forum#51]
Status does not change to shouldBeBanned when an unauthorized user tries to edit other post (gets insufficient_permissions error)

**Comment by dagansandler** [comment]
should work now

**Comment by dorleitman** [comment]
it still doesnt work...
I receive an error message when trying to remove or edit post of other user, but my status dosent changed to "ShoudBeBanned". 
Did it work for you?
